### ISSUE TITLE
ClassCastException : Vector drawable can not cast to LayerDrawable

### ISSUE THREAD

**Issue by cermohammadreza** [psinetron/slycalendarview#23]
When i click on the date following exception will throw :

    java.lang.ClassCastException: android.graphics.drawable.VectorDrawable cannot be cast to android.graphics.drawable.LayerDrawable

**Comment by cermohammadreza** [comment]
more detail : 
```    at ru.slybeaver.slycalendarview.GridAdapter.getView(GridAdapter.java:163)
        at android.widget.AbsListView.obtainView(AbsListView.java:2405)
        at android.widget.GridView.makeAndAddView(GridView.java:1459)
        at android.widget.GridView.makeRow(GridView.java:384)
        at android.widget.GridView.fillDown(GridView.java:325)
        at android.widget.GridView.fillSpecific(GridView.java:606)
        at android.widget.GridView.layoutChildren(GridView.java:1314)
        at android.widget.AbsListView.onLayout(AbsListView.java:2202)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3157)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2614)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
        at android.view.Choreographer.doFrame(Choreographer.java:726)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        ```
